/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xiecaibao_study_jnitest_Hello */

#ifndef _Included_com_example_xiecaibao_study_jnitest_Hello
#define _Included_com_example_xiecaibao_study_jnitest_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xiecaibao_study_jnitest_Hello
 * Method:    getFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xiecaibao_study_jnitest_Hello_getFromC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
